# Generated by Django 3.1.6 on 2021-04-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_auto_20210428_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orpodanieissues',
            name='bulletin_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v2.bulletinissues'),
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v2.companies'),
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='raw_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v2.rawissues'),
        ),
        migrations.AlterField(
            model_name='rawissues',
            name='bulletin_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v2.bulletinissues'),
        ),
    ]
